In [ ]:
import numpy as np
import pandas as pd
students = np.random.randint(50,101,size=(50,5))
stu = pd.DataFrame(students,
             columns=['國文','英文','數學','地理','歷史'],
             index=[f'第{i}號' for i in range(1,51)]
             )
stu

In [2]:
#使用query(),搜尋值
stu.query('國文<60')

      國文  英文  數學  地理  歷史
第3號   55  65  73  62  60
第5號   53  86  79  88  78
第15號  50  54  74  71  51
第16號  59  61  57  82  53
第22號  55  60  93  72  70
第23號  56  89  90  77  52
第28號  50  53  70  87  82
第31號  55  63  62  61  60
第41號  53  84  60  82  68
第44號  56  75  88  64  86